type Choice = string
type CorrectAnswers = string[]

export type Question = {
  question: string
  choices: Choice[]
  type: 'MCQs' | 'MAQs' | 'boolean'
  correctAnswers: CorrectAnswers
  score: number
  code?: string
  image?: null
}

export type Topic = {
  topic: string
  level: string
  totalQuestions: number
  totalScore: number
  totalTime: number
  questions: Question[]
}

export const mathematicsQuestions: Topic = {
    topic: 'Mathematics',
    level: 'Beginner',
    totalQuestions: 100,
    totalScore: 1000,
    totalTime: 100,
    questions: [
  
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
    ],
  }
  
  export const englishQuestions: Topic = {
    topic: 'English',
    level: 'Beginner',
    totalQuestions: 100,
    totalScore: 1000,
    totalTime: 100,
    questions: [
  
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `Synonym of 'Brave'?' `,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `Antonym of 'Dark'?' `,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `Verb in: 'The dog barked loudly.'?' `,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `Type of sentence: 'Please help me.'`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `Past tense of 'goes'?' `,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
    ],
  }
  
  export const generalknowledgeQuestions: Topic = {
    topic: 'GeneralKnowledge',
    level: 'Beginner',
    totalQuestions: 100,
    totalScore: 1000,
    totalTime: 100,
    questions: [
  
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: 'Find the LCM of 8 and 12.',
        image: null,
        choices: ['24', '12', '8', '48'],
        type: 'MCQs',
        correctAnswers: ['24'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: 'Area of rectangle (10 cm × 4 cm)?',
        image: null,
        choices: ['14', '40', '20', '100'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: '3/5 + 2/5 = ?',
        image: null,
        choices: ['1', '3/5', '5/10', '5/5'],
        type: 'MCQs',
        correctAnswers: ['5/5'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: `'Antonym of 'Dark'?'`,
        image: null,
        choices: ['Light', 'Bright', 'Gloomy', 'Shadow'],
        type: 'MCQs',
        correctAnswers: ['Light'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: 'Simplify: (8 + 2) × 5',
        image: null,
        choices: ['10', '40', '50', '30'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `'Verb in: 'The dog barked loudly.'?'`,
        image: null,
        choices: ['The', 'Dog', 'Barked', 'Loudly'],
        type: 'MCQs',
        correctAnswers: ['Barked'],
        score: 10,
      },
      {
        question: 'Seconds in 2 hours?',
        image: null,
        choices: ['120', '7200', '3600', '1800'],
        type: 'MCQs',
        correctAnswers: ['7200'],
        score: 10,
      },
      {
        question: `''____ apple a day...''`,
        image: null,
        choices: ['A', 'The', 'An', 'No article'],
        type: 'MCQs',
        correctAnswers: ['An'],
        score: 10,
      },
      {
        question: 'Convert 2.5 kg to grams.',
        image: null,
        choices: ['250g', '2500g', '25g', '2.5g'],
        type: 'MCQs',
        correctAnswers: ['2500g'],
        score: 10,
      },
      {
        question: 'Roman numeral for 59?',
        image: null,
        choices: ['LIX', 'LVIII', 'XLIX', 'LXI'],
        type: 'MCQs',
        correctAnswers: ['LIX'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Past tense of 'goes'?'`,
        image: null,
        choices: ['gone', 'went', 'going', 'go'],
        type: 'MCQs',
        correctAnswers: ['went'],
        score: 10,
      },
      {
        question: 'Square of 9?',
        image: null,
        choices: ['81', '18', '27', '72'],
        type: 'MCQs',
        correctAnswers: ['81'],
        score: 10,
      },
      {
        question: `'Adjective in: 'The tall boy won.'?'`,
        image: null,
        choices: ['boy', 'tall', 'won', 'The'],
        type: 'MCQs',
        correctAnswers: ['tall'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: 'What is 25% of 200?',
        image: null,
        choices: ['25', '50', '75', '100'],
        type: 'MCQs',
        correctAnswers: ['50'],
        score: 10,
      },
      {
        question: `''She _____ playing in the garden.''`,
        image: null,
        choices: ['were', 'was', 'is', 'are'],
        type: 'MCQs',
        correctAnswers: ['was'],
        score: 10,
      },
      {
        question: 'x + 15 = 30, find x',
        image: null,
        choices: ['30', '10', '15', '25'],
        type: 'MCQs',
        correctAnswers: ['15'],
        score: 10,
      },
      {
        question: 'Correct spelling?',
        image: null,
        choices: ['Recieve', 'Receive', 'Recive', 'Receeve'],
        type: 'MCQs',
        correctAnswers: ['Receive'],
        score: 10,
      },
      {
        question: `'Synonym of 'Brave'?'`,
        image: null,
        choices: ['Coward', 'Fearless', 'Weak', 'None'],
        type: 'MCQs',
        correctAnswers: ['Fearless'],
        score: 10,
      },
      {
        question: `'Type of sentence: 'Please help me.''`,
        image: null,
        choices: ['Exclamatory', 'Declarative', 'Interrogative', 'Imperative'],
        type: 'MCQs',
        correctAnswers: ['Imperative'],
        score: 10,
      },
      {
        question: `'Rearrange: 'quickly / the / ran / dog''`,
        image: null,
        choices: ['The dog quickly ran', 'The quickly ran dog', 'Dog the quickly ran', 'The dog ran quickly'],
        type: 'MCQs',
        correctAnswers: ['The dog ran quickly'],
        score: 10,
      },
    ],
  }
  
  export const reasoningQuestions: Topic = {
    topic: 'Reasoning',
    level: 'Beginner',
    totalQuestions: 100,
    totalScore: 1000,
    totalTime: 100,
    questions: [
  
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'Find the odd one out: Apple, Banana, Carrot, Mango',
        image: null,
        choices: ['Apple', 'Banana', 'Carrot', 'Mango'],
        type: 'MCQs',
        correctAnswers: ['Carrot'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Fill in the blank: 5, 10, 20, __, 80',
        image: null,
        choices: ['30', '35', '40', '50'],
        type: 'MCQs',
        correctAnswers: ['40'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: `'Unscramble: ‘LPEAP’'`,
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: 'Which number comes next: 2, 4, 6, 8, ?',
        image: null,
        choices: ['9', '10', '12', '14'],
        type: 'MCQs',
        correctAnswers: ['10'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'Which is the lightest?',
        image: null,
        choices: ['Iron', 'Cotton', 'Gold', 'Silver'],
        type: 'MCQs',
        correctAnswers: ['Cotton'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'Unscramble: ‘LPEAP’',
        image: null,
        choices: ['LAPEL', 'APPLE', 'PALEL', 'PLEAL'],
        type: 'MCQs',
        correctAnswers: ['APPLE'],
        score: 10,
      },
      {
        question: `'Mirror image of 'CAT' is?'`,
        image: null,
        choices: ['TAC', 'ʇ∀Ɔ', 'ACT', 'TCA'],
        type: 'MCQs',
        correctAnswers: ['ʇ∀Ɔ'],
        score: 10,
      },
      {
        question: 'What comes next in: A, C, E, G, ?',
        image: null,
        choices: ['H', 'I', 'J', 'K'],
        type: 'MCQs',
        correctAnswers: ['J'],
        score: 10,
      },
      {
        question: 'If CAT = 3-1-20, then DOG = ?',
        image: null,
        choices: ['4-15-7', '4-14-7', '4-15-6', '3-15-7'],
        type: 'MCQs',
        correctAnswers: ['4-15-7'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
      {
        question: 'Which shape is different?',
        image: null,
        choices: ['Circle', 'Triangle', 'Square', 'Cube'],
        type: 'MCQs',
        correctAnswers: ['Cube'],
        score: 10,
      },
      {
        question: 'If MONDAY is coded as 123456, then DAY = ?',
        image: null,
        choices: ['456', '654', '321', '345'],
        type: 'MCQs',
        correctAnswers: ['456'],
        score: 10,
      },
    ],
  }